from setuptools import setup, find_packages
import couchformation

from pathlib import Path
this_directory = Path(__file__).parent
long_description = (this_directory / "README.md").read_text()

setup(
    name='couchformation',
    version=couchformation.__version__,
    packages=find_packages(exclude=['tests']),
    url='https://github.com/mminichino/couch-formation-core',
    license='Apache License 2.0',
    author='Michael Minichino',
    python_requires='>=3.8',
    entry_points={
        'console_scripts': [
            'cloudmgr = couchformation.cli.cloudmgr:main',
            'dbdump = couchformation.cli.dbdump:main'
        ]
    },
    package_data={'couchformation': ['data/*']},
    install_requires=[
        "adal==1.2.7",
        "ansible==6.7.0",
        "ansible-core==2.13.13",
        "ansible-runner==2.3.4",
        "anyio==4.2.0",
        "applicationinsights==0.11.10",
        "argcomplete==3.1.6",
        "attrs==23.1.0",
        "azure-cli-command-modules-nspkg==2.0.3",
        "azure-cli-core==2.56.0",
        "azure-cli-nspkg==3.0.4",
        "azure-cli-telemetry==1.1.0",
        "azure-common==1.1.28",
        "azure-core==1.29.6",
        "azure-identity==1.14.0",
        "azure-mgmt-compute==30.1.0",
        "azure-mgmt-core==1.4.0",
        "azure-mgmt-network==25.1.0",
        "azure-mgmt-resource==23.0.1",
        "azure-mgmt-storage==21.1.0",
        "azure-mgmt-subscription==3.1.1",
        "azure-nspkg==3.0.2",
        "bcrypt==4.0.1",
        "bleach==6.0.0",
        "boto3==1.34.17",
        "botocore==1.34.17",
        "bump2version==1.0.1",
        "bumpversion==0.6.0",
        "cachetools==5.3.1",
        "cbcmgr==2.1.8",
        "certifi==2023.7.22",
        "cffi==1.15.1",
        "charset-normalizer==3.2.0",
        "click==8.1.7",
        "click-default-group==1.2.4",
        "click-default-group-wheel==1.2.3",
        "couchbase==4.1.8",
        "cryptography==41.0.7",
        "dnspython==2.4.2",
        "docker==6.1.3",
        "docutils==0.20.1",
        "exceptiongroup==1.1.3",
        "google-api-core==2.11.1",
        "google-api-python-client==2.98.0",
        "google-auth==2.22.0",
        "google-auth-httplib2==0.1.0",
        "google-cloud==0.34.0",
        "google-cloud-compute==1.14.0",
        "google-cloud-core==2.3.3",
        "google-cloud-network-management==1.11.0",
        "google-cloud-storage==2.10.0",
        "google-crc32c==1.5.0",
        "google-resumable-media==2.6.0",
        "googleapis-common-protos==1.60.0",
        "grpcio==1.57.0",
        "grpcio-status==1.57.0",
        "httplib2==0.22.0",
        "humanfriendly==10.0",
        "idna==3.4",
        "importlib-metadata==6.2.1",
        "importlib-resources==6.0.1",
        "iniconfig==2.0.0",
        "isodate==0.6.1",
        "jaraco.classes==3.3.0",
        "Jinja2==3.1.2",
        "jmespath==1.0.1",
        "keyring==24.2.0",
        "knack==0.11.0",
        "lockfile==0.12.2",
        "markdown-it-py==3.0.0",
        "MarkupSafe==2.1.3",
        "mdurl==0.1.2",
        "more-itertools==10.1.0",
        "msal==1.24.0b2",
        "msal-extensions==1.0.0",
        "msrest==0.7.1",
        "msrestazure==0.6.4",
        "numpy==1.24.4",
        "oauthlib==3.2.2",
        "overrides==7.4.0",
        "packaging==23.1",
        "pandas==2.0.3",
        "paramiko==3.3.1",
        "passlib==1.7.4",
        "pexpect==4.8.0",
        "Pillow==10.1.0",
        "pkginfo==1.9.6",
        "pluggy==1.3.0",
        "ply==3.11",
        "portalocker==2.7.0",
        "proto-plus==1.22.3",
        "protobuf==4.24.2",
        "psutil==5.9.6",
        "ptyprocess==0.7.0",
        "pyasn1==0.5.0",
        "pyasn1-modules==0.3.0",
        "pycparser==2.21",
        "pycryptodome==3.18.0",
        "Pygments==2.16.1",
        "pyhostprep==0.1.52",
        "PyJWT==2.8.0",
        "PyNaCl==1.5.0",
        "pyOpenSSL==23.3.0",
        "pyparsing==3.1.1",
        "PySocks==1.7.1",
        "pytest==7.4.0",
        "pytest-asyncio==0.21.1",
        "pytest-mock==3.12.0",
        "pytest-rerunfailures==12.0",
        "python-daemon==3.0.1",
        "python-dateutil==2.8.2",
        "pytz==2023.3.post1",
        "pyvmomi==8.0.1.0.2",
        "PyYAML==6.0.1",
        "readme-renderer==41.0",
        "requests==2.31.0",
        "requests-oauthlib==1.3.1",
        "requests-toolbelt==1.0.0",
        "resolvelib==0.8.1",
        "rfc3986==2.0.0",
        "rich==13.5.2",
        "rsa==4.9",
        "s3transfer==0.10.0",
        "six==1.16.0",
        "sniffio==1.3.0",
        "sqlite-fts4==1.0.3",
        "sqlite-utils==3.35",
        "tabulate==0.9.0",
        "tomli==2.0.1",
        "twine==4.0.2",
        "typing_extensions==4.7.1",
        "tzdata==2023.3",
        "uritemplate==4.1.1",
        "urllib3==1.26.18",
        "webencodings==0.5.1",
        "websocket-client==1.6.2",
        "xmltodict==0.13.0",
        "zipp==3.16.2",
    ],
    author_email='info@unix.us.com',
    description='Couchbase Cloud Automation',
    long_description=long_description,
    long_description_content_type='text/markdown',
    keywords=["couchbase", "devops", "automation"],
    classifiers=[
        "Development Status :: 4 - Beta",
        "License :: OSI Approved :: Apache Software License",
        "Intended Audience :: Developers",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Topic :: Database",
        "Topic :: Software Development :: Libraries",
        "Topic :: Software Development :: Libraries :: Python Modules"
    ],
)
